changed handling of the XRIT_DECOMPRESS_OUTDIR
one common XRIT_DECOMPRESS_OUTDIR for everybody
changed in mipp accordingly that everybody in the group
has reading and writing rights, to delete decompressed files
of the others

diff --git a/setup/bashrc_offline b/setup/bashrc_offline
--- a/setup/bashrc_offline
+++ b/setup/bashrc_offline
@@ -9,26 +9,60 @@ fi
 
 #PS1='\[[\u@ \e[1;31m\]\h \e[0;37m\W]\$\[\e[0m\] '
 
+# when using cronjobs a few common shell variables are not set
+if ! test -n "${HOSTNAME}"; then
+    export HOSTNAME=`/bin/hostname` 
+    echo '... set HOSTNAME to:' ${HOSTNAME}
+fi
+if ! test -n "${USER}"; then
+    export USER=${LOGNAME}
+    echo '... set USER to:' ${LOGNAME}
+fi
+if ! test -n "${logname}"; then
+    export logname=${LOGNAME}
+    echo '... set logname to:' ${LOGNAME}
+fi
+
+
 echo "USER" ${USER}
 echo "\$(logname)" $(logname)
 echo "\$LOGNAME" $LOGNAME
 echo "uname -mrs:" `uname -mrs`
+echo "whoami:" `/usr/bin/whoami`
+
+case $HOSTNAME in
+    "zueub"[2-4][0-9][0-9])
+	if [ -d /opt/users/$LOGNAME/monti-pytroll/ ]
+        then
+            #source /opt/users/$LOGNAME/monti-pytroll/setup/set_paths.sh   # source is not supported by cronjobs
+	    . /opt/users/$LOGNAME/monti-pytroll/setup/set_paths.sh
+        else
+            #source /opt/users/$LOGNAME/PyTroll/setup/set_paths.sh         # source is not supported by cronjobs
+	    . /opt/users/$LOGNAME/PyTroll/setup/set_paths.sh
+        fi
+	;;
+    "keschln-"[0-9][0-9][0-9][0-9]|"ela"[0-9])
+        # tmp !!!! BAD DIRTY FIX !!!!
+        export LOGNAME_ORG=$LOGNAME
+        export LOGNAME=hamann
+	# source /users/$LOGNAME/monti-pytroll/setup/set_paths.sh  # load functions from this script
+	. /users/$LOGNAME/monti-pytroll/setup/set_paths.sh
+	;;
+    *)
+	echo "ERROR (1) in setup/bashrc: unknown computer ---"$HOSTNAME"---"
+	return ;;
+	#exit 1 ;;
+esac
+
+set_utils_path
+set_conda_path
+set_pytroll_paths
+
+export PPP_CONFIG_DIR=$PYTROLLHOME/cfg_offline/
+echo "... set PPP_CONFIG_DIR to: "$PPP_CONFIG_DIR
 
 case $HOSTNAME in
 "zueub"[2-4][0-9][0-9])
-    if [ -d /opt/users/$LOGNAME/monti-pytroll/ ]
-    then
-	export PYTROLLHOME=/opt/users/$LOGNAME/monti-pytroll/
-    else
-	export PYTROLLHOME=/opt/users/$LOGNAME/PyTroll/	
-    fi
-    export PPP_CONFIG_DIR=$PYTROLLHOME/cfg_offline/
-    export XRIT_DECOMPRESS_PATH=/opt/users/common/bin/xRITDecompress
-    export XRIT_DECOMPRESS_OUTDIR=/tmp/SEVIRI_DECOMPRESSED_$LOGNAME
-    export UTILS_PATH=/opt/users/common/
-    export CONDA_PATH="/opt/users/common/packages/anaconda3/"
-    export PATH=$CONDA_PATH"/bin:$PATH"
-
     # special settings only for zueub computers
     alias tkdiff='echo tkdiff is too old, use \"meld\" instead; echo  meld '
     export http_proxy=http://proxy.meteoswiss.ch:8080
@@ -46,43 +80,28 @@ case $HOSTNAME in
     #	alias tkdiff='/opt/users/common/packages/tkdiff-unix/tkdiff'
     #fi
     ;;
-"keschln-0002")
-    export PYTROLLHOME=$HOME/monti-pytroll/
-    export PPP_CONFIG_DIR=$PYTROLLHOME/cfg_offline/
-    export XRIT_DECOMPRESS_PATH=/store/mch/msrad/sat/pytroll/xRITDecompress
-    export XRIT_DECOMPRESS_OUTDIR=/scratch/$LOGNAME
-    export UTILS_PATH=/store/msrad/sat/
-    export CONDA_PATH="/store/msrad/utils/anaconda3/"
+"keschln-"[0-9][0-9][0-9][0-9]|"ela"[0-9])
     ;;
 *)
-    echo "ERROR in check_hostname: unknown computer"
-    exit 1
+    echo "ERROR in bashrc: unknown computer "$HOSTNAME
+    return
     ;;
 esac
-
-export PATH=$CONDA_PATH"/bin:$PATH"
-export PSP_CONFIG_FILE=${UTILS_PATH}/packages/pyspectral_aux_files/pyspectral.cfg
-#unset PSP_CONFIG_FILE   # should not be needed any more ... 
-
-# added by Anaconda3 4.0.0 installer
-conda -V
-which conda
-which python
-
-# easy access to the easy-install file
-alias easy-install.pth='emacs '$CONDA_PATH'/envs/PyTroll_$LOGNAME/lib/python2.7/site-packages/easy-install.pth &'
 
 #export PY_SHAPEFILES=$PYTROLLHOME/shapes/
 
 export PYTHONPATH=$CONDA_PATH/bin:$PYTROLLHOME/scripts
 
-# easier activation and deactivation of the virtual environment PyTroll
-alias activate='source activate PyTroll_$LOGNAME'
-alias deactivate='source deactivate'
+# activate virtual environment
 source activate PyTroll_$LOGNAME
 
 # some useful alias commands
 alias ll='ls --color=auto -alh'
 alias ls='ls --color=auto'
 
-#alias cdo='/opt/users/common/lib/cdo-1.7.1/bin/cdo'
+# tmp !!!! BAD DIRTY FIX !!!!
+case $HOSTNAME in
+    "keschln-"[0-9][0-9][0-9][0-9]|"ela"[0-9])
+	export LOGNAME=$LOGNAME_ORG
+	;;
+esac
